DROP TABLE IF EXISTS patch CASCADE;
DROP TABLE IF EXISTS tute CASCADE;
DROP TABLE IF EXISTS maglie CASCADE;
DROP TABLE IF EXISTS vendite CASCADE;
DROP TABLE IF EXISTS richieste CASCADE;
DROP TABLE IF EXISTS prodotti CASCADE;

CREATE TABLE prodotti (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tipo TEXT NOT NULL DEFAULT 'patch',
  titolo TEXT NOT NULL,
  descrizione TEXT NOT NULL DEFAULT '',
  prezzo_acquisto NUMERIC(10,2) NOT NULL DEFAULT 0,
  quantita INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE richieste (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  titolo TEXT NOT NULL,
  link TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE prodotti ENABLE ROW LEVEL SECURITY;
ALTER TABLE richieste ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all operations on prodotti" ON prodotti FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations on richieste" ON richieste FOR ALL USING (true) WITH CHECK (true);
